In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df=pd.read_csv('/content/heart.csv')
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
X=

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=42)

In [ ]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [ ]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [ ]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8852459016393442
Accuracy of Decision Trees 0.8360655737704918

In [11]:
confusion_matrix(y_test,y_pred1)

array([[25,  4],
       [ 3, 29]])

In [12]:
confusion_matrix(y_test,y_pred2)

array([[26,  3],
       [ 7, 25]])

In [13]:
pd.DataFrame(confusion_matrix(y_test,y_pred1))

    0   1
0  25   4
1   3  29

In [15]:
result=pd.DataFrame()
result['actual result']=y_test
result['logistic result']=y_pred1
result['decision result']=y_pred2

In [16]:
result.sample(10)

     actual result  logistic result  decision result
175              0                0                1
223              0                0                0
45               1                1                1
42               1                0                1
192              0                0                0
25               1                1                1
78               1                1                1
111              1                1                0
285              0                0                0
125              1                1                1

In [19]:
from sklearn.metrics import f1_score,recall_score,precision_score

In [21]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print('f1_score-',f1_score(y_test,y_pred1))
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  25   4
1   3  29
--------------------------------------------------
f1_score- 0.8923076923076924
Precision -  0.8787878787878788
Recall -  0.90625

In [22]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  26   3
1   7  25
--------------------------------------------------
Precision -  0.8928571428571429
Recall -  0.78125
F1 score -  0.8333333333333334

In [25]:
precision_score(y_test,y_pred1,average=None)

array([0.89285714, 0.87878788])

In [26]:
precision_score(y_test,y_pred2,average=None)

array([0.78787879, 0.89285714])

In [27]:
recall_score(y_test,y_pred1,average=None)

array([0.86206897, 0.90625   ])