In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Species']=le.fit_transform(df['Species'])

In [8]:
df.sample(10)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
92    93            5.8           2.6            4.0           1.2        1
13    14            4.3           3.0            1.1           0.1        0
20    21            5.4           3.4            1.7           0.2        0
103  104            6.3           2.9            5.6           1.8        2
47    48            4.6           3.2            1.4           0.2        0
138  139            6.0           3.0            4.8           1.8        2
61    62            5.9           3.0            4.2           1.5        1
4      5            5.0           3.6            1.4           0.2        0
6      7            4.6           3.4            1.4           0.3        0
82    83            5.8           2.7            3.9           1.2        1

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [11]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [12]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 1.0
Accuracy of Decision Trees 0.9666666666666667

In [20]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
33              0                               0                         0
77              1                               1                         1
102             2                               2                         2
98              1                               1                         1
141             2                               2                         2
40              0                               0                         0
78              1                               1                         1
125             2                               2                         2
73              1                               1                         1
120             2                               2                         2

In [13]:
from sklearn.metrics import recall_score,f1_score,precision_score

In [17]:
print(recall_score(y_test,y_pred1,average='macro'))

1.0

In [18]:
print(f1_score(y_test,y_pred1,average='macro'))

1.0