In [1]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv('/content/play_tennis.csv')
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

Calculating Class Probabilities ($P(\text{Yes})$ and $P(\text{No})$)

In [6]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py=9/14
pn=5/14

In [14]:
pd.crosstab(data['outlook'], data['play'])
pd.crosstab(data['temp'], data['play'])
pd.crosstab(data['humidity'], data['play'])
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [15]:
# Outlook probabilities
p_overcast_no = 0 / 5
p_rain_no = 2 / 5
p_sunny_no = 3 / 5

p_overcast_yes = 4 / 9
p_rain_yes = 3 / 9
p_sunny_yes = 2 / 9

# Temperature probabilities
p_cool_no = 1 / 5
p_hot_no = 2 / 5
p_mild_no = 2 / 5

p_cool_yes = 3 / 9
p_hot_yes = 2 / 9
p_mild_yes = 4 / 9

# Humidity probabilities
p_high_no = 4 / 5
p_normal_no = 1 / 5

p_high_yes = 3 / 9
p_normal_yes = 6 / 9

# Wind probabilities
p_strong_no = 3 / 5
p_weak_no = 2 / 5

p_strong_yes = 3 / 9
p_weak_yes = 6 / 9

In [16]:
# Calculate probability proportional to P(Yes | X)
p_yes_given_x = py * p_sunny_yes * p_hot_yes * p_high_yes * p_weak_yes

# Calculate probability proportional to P(No | X)
p_no_given_x = pn * p_sunny_no * p_hot_no * p_high_no * p_weak_no

print("P(Yes|X):", p_yes_given_x)
print("P(No|X):", p_no_given_x)

# Final Decision (MAP Rule)
if p_yes_given_x > p_no_given_x:
    print("Prediction: Yes")
else:
    print("Prediction: No")

P(Yes|X): 0.007054673721340388
P(No|X): 0.02742857142857143
Prediction: No